### ISSUE TITLE
[CODE REVIEW] 1.x Overhaul Review

### ISSUE THREAD

**Issue by wadetandy** [jsonapi-suite/jsorm#38]
This it the place for placing outstanding issues for cleanup before the first 1.0.0 release candidate can be cut.  Branch with latest and greatest is [here](https://github.com/jsonapi-suite/jsorm/tree/1.x-dev).

**Comment by wadetandy** [comment]
Looking for opinions on [these exports](https://github.com/jsonapi-suite/jsorm/blob/1.x-dev/src/index.ts#L8-L20). They are identically named but have different cases. One is for the old `Model.extend()` api and the other is for the decorators api.  Open to changes in naming or potentially doing some additional magic to consolidate these into a single method based on argument type (if possible from a typings perspective).

**Comment by wadetandy** [comment]
Currently [`JSORMBase#id` is `string | undefined`](https://github.com/jsonapi-suite/jsorm/blob/1.x-dev/src/model.ts#L166), which is technically correct but also means that with strict typing enabled, you always have to check for it:

``` typescript
const loadEmployee(id : string) => {/**/}

EventBus.$on('employee_selected',(employee : Employee) => {
  let id = employee.id

  if(id) { // have to check this or loadEmployee blows since it expects a string
    loadEmployee(id)
  }
})
``` 

I lean toward keeping `id` always a string and having `model.isPersisted` being the right check, but I'm only like 53% sure of that. It's technically wrong but nicer for dev experience.

**Comment by richmolj** [comment]
The `string | undefined` issue I run into a lot with TS, where TS has the technical definition correct but there's no way it will ever reach the function that way. I don't think this function should have a check at all.

The best I can think of is a separate `JSONAPIIdentifier` type, which is `string | undefined`. That way the `loadEmployee` function could accept `JSONAPIIdentifier` and the check would pass.

All that said, I think this is a great example of where Apps (not libs) should have less strict typings. Is there any way we can toggle off this check, or otherwise globally handle the "or undefined" case?

**Comment by richmolj** [comment]
I think I'm fine with the exports as long as we have a comment. Consolidating into a single method I'm not against, but it seems like the additional complexity would outweigh the benefit.

**Comment by wadetandy** [comment]
Any application can make this problem go away by disabling the `strictNullChecks` typescript compile option, though I think there are generally a lot of benefits for that compile option and I feel like it's among the more useful type warnings in a system with correct types. That said teams that don't care about this class of errors can avoid it by disabling that option.  Then we get to keep good typing for teams that want it, which I think should be the preferred approach.
