### ISSUE TITLE
Dirty tracking: your custom implementation vs mobx-utils viewModel

### ISSUE THREAD

**Issue by swrobel** [jsonapi-suite/jsorm#87]
Is there any reason you chose not to use [viewModel](https://github.com/mobxjs/mobx-utils#viewmodel)?

**Comment by richmolj** [comment]
Not explicitly, no, actually not familiar with this library. One issue would be dealing with dirty relationships, though, I'm not sure how that would work here. IOW `post.isDirty()` could return false while `post.isDirty({ comments: "author" })` is true because the author for a given comment changed.

Not against anything in premise, though - was there something in `viewModel` you feel we're missing?

**Comment by swrobel** [comment]
My mistake, I thought jsorm depended on mobx. I just admire your implementation, so I figured I'd ask. It's definitely a complex (and rarely-implemented) feature!
