### ISSUE TITLE
Shouldn't association decorators return a descriptor?

### ISSUE THREAD

**Issue by hector** [jsonapi-suite/jsorm#99]
I am under the impression a return is missing in this line, so the descriptor is returned and the property is correctly defined. Without it I can only declare associations (e.g. BelongsTo) outside of a class.
https://github.com/jsonapi-suite/jsorm/blob/61026e1c2a5305e4752422f42c6158a964953358/src/decorators.ts#L223

**Comment by wadetandy** [comment]
This is related to https://github.com/jsonapi-suite/jsorm/issues/85.  Essentially typescript and Babel decorators have slightly different behavior, and our decorators here only work with typescript at the moment.  The major blocker here is having a post-build test setup for es6/babel to run against the compiled version of the library so that we can start creating fixes for issues like this.

**Comment by wadetandy** [comment]
@hector just pushed https://github.com/jsonapi-suite/jsorm/releases/tag/v1.3.2 out.  Please let us know whether this fixes your issue!

**Comment by hector** [comment]
It seems like there was already a 1.3.2 release on NPM without this fix. I cannot get the version with the fix

**Comment by richmolj** [comment]
@hector I just published `1.3.3`, does that work for you?

**Comment by hector** [comment]
Yes, finally!! Very cool
